config/routes.rb
Rails.application.routes.draw do

  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'words#index', as: :authenticated_root
  end

  unauthenticated do
    root 'about#index', as: :unauthenticated_root
  end
end

  get 'about' => 'about#index'

  resources :words
  root 'words#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user
        can :create, @word
        can :update, Word, :user_id => user.id
        can :destroy, Word, :user_id => user.id
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :words, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :user

	validates :img, presence: true ## implemented using the button create
	validates :word, presence: true
	validates :desc, presence: true
	validates :user_id, presence: true


  has_attached_file :img, :s3_protocol => :https, styles: { medium: "650x400>", thumb: "100x100>" }, default_url: "/imgs/:style/imgD.jpg"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/

	if Rails.env.development?
  		has_attached_file :fichier,
    	:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    	:url => "/system/:attachment/:id/:style/:filename"
	end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	#For Locale
#  	around_action :with_locale


	# CanCanCan expects a current_user method to exist in the controller
	# - > include CanCan 
	include CanCan::ControllerAdditions
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception


#private
#  def with_locale
#    I18n.with_locale(params[:locale]) { yield }
#  end
#
#  def default_url_options(options = {})
#    { locale: I18n.locale }
#  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  
  #load_and_authorize_resource ## for CanCan control
  before_filter :authenticate_user!
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    ## perform a paginated query
    ## use current_user for view current_user.words
    @words = current_user.words.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    
    #Decode in *.png
    require 'base64'

    @word = current_user.words.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:img, :word, :desc, :user_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/about/index.html.erb
<div class="jumbotron">
		<h1>ImgDictionary</h1>
		<h2>Изучайте иностранные слова с помощью рисования изображений-ассоциаций</h2>
		<br>

  	    <% if !user_signed_in? %>
			<%= link_to new_user_session_path, :class => "btn btn-success btn-lg" do %>
			  <span class="glyphicon glyphicon-log-in"></span>
			  <%= t('menu.login') %>
			<% end %>

			<%= link_to new_user_registration_path, :class => "btn btn-primary btn-lg" do %>
			  <span class="glyphicon glyphicon-ok"></span>
			  <%= t('menu.reg') %>
			<% end %>
        <% end %>
</div>

<div class="row">
  <div class="container">
     <div class="well well-lg">
          
      <h3>Все что тебе нужно:
      <br><strong>Желание</strong>
      <br><strong>Воображение</strong>
      </h3>
      <br>Хорошо запоминается то, над чем мы долго практикуемся</p>
      <br>ImgD предоставляет именно это
      <br>Здесь не будет волшебных таблеток или мотивационных пожеланий
      <br>Но если ты хочешь выучить язык и тебе нужен еще один вид практики - это приложение для тебя
      <br>
      <h3>Схема работы</h3>
      <li>Добавляешь иностранное слово или фразу</li>
      <li>Пишешь перевод</li>
      <li>Представляешь в воображении ассоциацию</li>
      <li>Рисуешь ассоциацию и закрепляешь нарисованное в голове</li>
      Ты работаешь над этим словом, придумываешь ассоциацию, рисуешь ее
      <br>Теперь ты имеешь практический опыт со словом
      <br>
      А значит и знаешь его :)
    </div>
  </div>
</div>
        </div>

app/views/layouts/_draw.html.erb
  <style>
  /* Customize container */
  @media (min-width: 768px) {
    .container {
      max-width: 730px;
    }
  }
  </style>
  <script type="text/javascript">
    var editor1 = null;
    $(function(){

    editor1 = new editor('view', 650, 400);

    //Create word img button
    $('body').on('click','#click_save_img', function(image){
      document.getElementById('word_img').value = editor1.getImage();
      console.log("onSave click target");
    });

    //Standart button
    editor1.onSave(function(image){
        document.getElementById('word_img').value = image;
        console.log("onSave");
    });
      });

   function startTimer() {
      var my_timer = document.getElementById("my_timer");
      var time = my_timer.innerHTML;

      var arr = time.split(":");
      var h = arr[0];
      var m = arr[1];
      var s = arr[2];
      if (s == 0) {
        if (m == 0) {
          if (h == 0) {
            $('#click_save_img').removeClass( 'disabled' );
            return;
          }
          h--;
          m = 60;
          if (h < 10) h = "0" + h;
        }
        m--;
        if (m < 10) m = "0" + m;
        s = 59;
      }
      else s--;
      if (s < 10) s = "0" + s;
      document.getElementById("my_timer").innerHTML =h+":"+m+":"+s;
      setTimeout(startTimer, 1000);
    }

      //call startTimer();
      var ready;
      ready = function() {
        startTimer();
      };
      $(document).ready(ready);
      $(document).on('page:load', ready);


      //Disable button new word
      $("#click_save_img").addClass("disabled");
      //if you click close_timer
      $('body').on('click','#close_timer', function(image){
          alert("You shut down timer");
          $('#click_save_img').removeClass( 'disabled' );
      });

  </script>
  <div class="container">
    <div class="alert alert-dismissible alert-success">
      <button type="btn" class="close" id="close_timer" data-dismiss="alert">x</button>
      <p><%= t('timer.start_status') %> <strong><span id="my_timer">00:05:00</span></strong> <%= t('timer.end_status') %></p>
    </div>
  <div class="well" id="view">
  </div>
    </div>

app/views/layouts/_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top red">
  <div class="container">
    <div class="navbar-header">
        <%= link_to root_path, class: "navbar-brand"  do %>
            <span class="glyphicon glyphicon-book"></span>
            <%= t('menu.name') %>
        <% end %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to t('menu.about'), about_path %>
        </li>
        <li>
          <%= link_to t('menu.help'), about_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if I18n.locale == I18n.default_locale %>
            <%= link_to "En", :locale=>'en'%>
          <% else %>
            <%= link_to "Ru", :locale=>'ru'%>
          <%end%>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <%= t('menu.logout') %>
              <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span>
              <%= t('menu.login') %>
            <% end %>
        </li>
        <li>
              <%= link_to t('menu.reg'), new_user_registration_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>ImgD</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
	<%= render 'layouts/menu' %>
	<br>
	<div class='container'>
		<div class='row'>
			<%= yield %>
		</div>
	</div>
	
	<br>
	<% render 'layouts/footer' %>
</body>
</html>

app/views/words/_form.html.erb
<%= form_for @word, class: 'form-horizontal', url: words_path, html: { multipart: true } do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'layouts/draw' %>
  <div class="field">
    <%= f.hidden_field :img %>
  </div>
  <div class="form-group">
    <%= f.label :word, t('words.word'), class: 'control-label' %><br>
    <%= f.text_field :word, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :desc, t('words.desc'), class: 'control-label' %><br>
    <%= f.text_field :desc, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :id => "click_save_img", class: 'btn btn-default', value: t('words.submit') %>
  </div>  
<% end %>

app/views/words/edit.html.erb
<legend><%= t('words.edit') %></legend>

<%= render 'form' %>

<%= link_to t('control.back'), words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Words:</h1>
<% if can? :create, @word %>
  <%= link_to t('words.new'), new_word_path, class: 'btn btn-primary btn-sm' %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th class="col-md-2"><%= t('words.img-association') %></th>
      <th class="col-md-4"><%= t('words.word') %></th>
      <th class="col-md-4"><%= t('words.desc') %> <%= image_tag('eye.png', id: 'eye', size: '16') %> </th>
      <th class="col-md-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= image_tag word.img.url(:medium), size: '325x200' %></td>
        <td><%= word.word %></td>
        <td class='Description'><%= word.desc %></td>
        <td>
<% if can? :update, word %>
        <%= link_to edit_word_path(word)  do %>
            <span class="glyphicon glyphicon-pencil"></span>
            <%= t('control.edit') %>
        <% end %>
<% end %>
<% if can? :destroy, word %>
        <br>
        <%= link_to word, method: :delete, data: { confirm: t('control.sure') }  do %>
            <span class="glyphicon glyphicon-trash"></span>
            <%= t('control.destroy') %>
        <% end %>
<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, @word %>
  <%= link_to t('words.new'), new_word_path, class: 'btn btn-primary btn-sm' %>
<% end %>
<br>
<%= will_paginate @words, renderer: BootstrapPagination::Rails %>
<br>

<script>
//View Description
$('body').on('click','#eye', function(){
    $(".Description").toggle(10);
});
</script>

app/views/words/new.html.erb
<legend><%= t('words.new') %></legend>

<%= render 'form' %>

<%= link_to t('control.back'), words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-2"><%= t('words.img-association') %></th>
      <th class="col-md-4"><%= t('words.word') %></th>
      <th class="col-md-4"><%= t('words.desc') %></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= image_tag @word.img.url(:medium) %></td>
        <td><%= @word.word %></td>
        <td class='Description'><%= @word.desc %></td>
      </tr>
  </tbody>
</table>

<%= link_to t('control.edit'), edit_word_path(@word) %> |
<%= link_to t('control.back'), words_path %>